- name: Install personal Arch Linux system
  hosts: localhost
  tasks:
  - name: Install personal packages
    pacman:
      state: present
      name:
        - gnucash
        - geary
        - digikam
        - pcsclite
        - mediathekview
  - name: Enable and start services
    systemd:
      unit: "{{ item }}"
      enabled: true
      state: started
    loop:
      # Smartcard services for eID
      - pcscd.socket
  - name: Configure NTP servers
    lineinfile:
      path: /etc/systemd/timesyncd.conf
      insertafter: "#NTP="
      regexp: "^NTP *="
      line: NTP={{ servers | join(' ') }}
    vars:
      servers:
        - ntp1.t-online.de
        - 0.de.pool.ntp.org
        - 1.de.pool.ntp.org
        - 2.de.pool.ntp.org
        - 3.de.pool.ntp.org
    notify:
    - Restart systemd-timesyncd
  - name: Install flatpaks
    flatpak:
      name: "{{ item }}"
      state: present
    loop:
      - com.skype.Client
      - com.valvesoftware.Steam

  - name: Packages from AUR and my local repo
    pacman:
      state: present
      name:
      - cozy-audiobooks
      - chiaki-git
      - pcsc-cyberjack
      - ausweisapp2

  handlers:
  - name: Restart systemd-timesyncd
    systemd:
      unit: systemd-timesyncd
      state: restarted
